### PR TITLE
WIn32 build fix and now check default directory if no registry entries

### PR DESCRIPTION
**Pull request by acotty**
@obfuscated This PR contains the following two changes that I did since the last last changes:

    Move the #include <wx/msw/registry.h>so C::B win32 builds do not fail.
    Added wxDirExists in case the registry does not have the Cygwin entries.

Today I also changed the wxString() to wxEmptyString to match the other changes that you have been doing lately.

### CODE REVIEW

**Comment by obfuscated** [comment]
> Today I also changed the wxString() to wxEmptyString to match the other changes that you have been doing lately.

This is backwards. The idea is to remove wxEmptyString and to replace it with wxString()...

**Comment by obfuscated** [comment]
Also which win32 build fail? Mine built successfully (wx31_64+pch).

**Comment by acotty** [comment]
Reverted the wxEmptyString change. Must have had the files in the wrong order.

wx31_64+pch works, but w31 did not for me.

**Comment by obfuscated** [comment]
FYI: Your crlf setting in git is incorrect. You're putting windows eol characters in source files and you're not supposed to do that. Please fix the setting.

**Comment by acotty** [comment]
Thanks for the post. Its not git my Git settings as it is set to not change the EOL as this is the best setting when working on Windows and Linux. The problem is with either the merge app I use or one of the editors I may have used.

I need to figure out which one is doing it.

**Comment by acotty** [comment]
I found the offending program, it's Winmerge 2.16.14.0 that when editing the merged code to add a new line adds the line with CRLF even though I have the settings to preserve original EOL characters..

**Comment by obfuscated** [comment]
> Thanks for the post. Its not git my Git settings as it is set to not change the EOL as this is the best setting when working on Windows and Linux.

This is incorrect on windows you should have windows eol characters and on linux you should have linux eol. And these conversions should be done by git. Any other solution would lead to this broken situation.

**Pull request closed without merging**
