### PR TITLE
Update Cygwin GDB support so it now works.

### PR DESCRIPTION
**Pull request by acotty**
This PR is done so that in future any Cygwin user who searches for a GDB fix can hopefully find it.

I do not have time to update/create/modify any of the test cases as I cannot find any existing test cases that use the functions I have modified. I have also checked and could not find any changes made to the gdb_driver.cpp include any test changes for the last few years that I checked.

### CODE REVIEW

**Comment by obfuscated** [comment]
Can you write a comment explaining what you do, why you do it and so on? I'm not a cygwin user, so I need some help understand the actual problems you're trying to solve.

**Comment by acotty** [comment]
Currently Codeblcoks Cygwin GDB support assumes "normal" windows drive lettering and directory structure, but under Cygwin the drive letters and directory structure look like Linux. So part of the changes is to change the way Codeblocks resolves drive/directory structure when running on Windows with Cygwin. (BTW MSYS2 and MinGW do NOT need these changes!!!)

This causes the debugging of an exe with debug enabled to not be able to load the source file, so in essence you cannot do any source level debugging in codeblocks when using Cygwin.

The other issues is that the code to detect Cygwin does not work correctly as it changed a long time ago, but the code in Codeblcosk was not updated for the Cygwin changes and as such the code to detected Cygwin has been updated to detect Cygwin.

After making the changes I spotted that the code kept processing the filename translation from Cygwin to Windows allot, so I added caching of this to speed things up. This is only applicable for Cygwin and is in the CorrectCygwinPath() finction.

These changes should all have either macro around them or call the Cygwin code detection or be in the Cygwin detection or file directory changes (with the exception of the addition of the isFileUpdated boolean) and if not then do NOT merge the code as all of the changes are specific for Cygwin.

**Comment by obfuscated** [comment]
> These changes should all have either macro around them or call the Cygwin code detection or be in the Cygwin detection or file directory changes (with the exception of the addition of the isFileUpdated boolean) and if not then do NOT merge the code as all of the changes are specific for Cygwin.

What do you mean by this? Are the changes complete? If they aren't merge-able what is the meaning of this PR?

**Comment by acotty** [comment]
I made the changes a while ago and have not looked at them for a while and when I did the changes I made it so that the changes would only affect Cygwin and no other compilers. If any are missing let me know as I need to update it, but I could not see any.

The changes are complete and I tested it with Cygwin and MSYS2 (effectively Mingw64) without any problems when I did the changes last year.

**Comment by obfuscated** [comment]
Are you using Cygwin actively? If I merge these changes can I expect them to work fine? I'm not a Cygwin/msys2 user, so I cannot tell if something is a good idea or not, I have to accept external contributions and I'm fine with them as long as they don't break the native debugging.

**Comment by acotty** [comment]
Sorry for the delay. I rebuilt CB trunk yesterday with WXWidget 3.1.5 to double check that nothing had changed since I last worked on the code and I am now getting a crash when trying to build a simple C++ test file. Will ask in the forum for some help/pointers.

**Comment by acotty** [comment]
Looks like the Cygwin GDB is now not consuming windows paths and needs a cygwin path. I have got this working. 

I have Cygwin building and debugging a simple test example CPP file and I also have MSYS2 mingw64 debugging working with the same codeblocks built exe/dll's, but when swapping between the two compiler setups the code keeps trying to use the Cygwin GDB debugger with the MSYS2 compiler. This would have been the case with the existing code if it worked as the existing code does not check to see what compiler you are trying to use if you have Cygwin and another compiler setup on the one PC!! Working on this change so the end user can swap between Cygwin and MSYS2. 

I probably should setup mingw64 again for testing. I have VS2019 CE installed, so I can test this later.

**Comment by acotty** [comment]
The existing CB code does not swap debuggers when you select a different default compiler in a project. 

I am able to swap between Cygwin and MSYS2 debuggers by using two different projects and swap between the projects or change the compiler in the project,save project, exit CB and run CB again with the updated project.

I am able to have the Cygwin and MSYS 2 projects loaded at the same time and swap between the two as well and the correct debugger is loaded for the applicable project being built/debugged.

The updated changes are included in this PR now.

**Comment by obfuscated** [comment]
Where is the code doing the detection if a cygwin mode should be used? Isn't it better to just put it somewhere as an option?

I've answered about the switching on the forum, please keep the discussion there.

**Comment by acotty** [comment]
The code to detect Cygwin in the debugeer code is in the DetectCygwinMount() function. The DetectCygwinMount first checks to ensure that the compiler is configured for Cygwin and then if it is then checks if Cygwin old or new configuration is setup in the Windows registry and if it is it uses these values to check that Cygwin is in the directory specified and if not then it will use the default C:\Cygwin64 to see if it exists and if it does then it will use this directory.

If cygwin is found then the m_CygwinPresent variable is set to true.

As for making it an option I have used the compiler GetCompilerID() as "cygwin" (see lines 279 through 317 in the gdb_drvier.cpp for this check) as THE option to check that the user wants to use the Cygwin GDB debugger as they go together and the user should hopefully will not create a new user compiler configuration for Cygwin as it would then break this check.

It would be nice to move this Cygwin detection and path/file conversion code in thee gdb_drive.cpp and the similar code in the compilerCYGWIN.cpp file into a common file, but these are in different DLL's and such should probably be in some other area in the code, like the SDK. What do you think about this?

**Comment by acotty** [comment]
I have moved the Cygwin detection and path conversion into the SDK so these functions can then be used by the debugger plugin and the compiler plugins.  One side affect of this was that I moved the g_EscapeChar into globals.cpp * .h file as it made sense so it can be used by other plugins.
This change now cleans the src/plugins/compilergcc/compilerCYGWIN.cpp  &  src/plugins/debuggergdb/gdb_driver.cpp  a heck of allot and makes them easier to read and understand IMHO.
It also means that most of the Cygwin specific code is now in the one file.
While I was modifying the global.cpp I also fixed a compiler warning in it.

Are the changes more acceptable?
Is the src/sdk/globals_CygWin.cpp appropriate and if not let me know what is a more suitable name.

If the changes are okay do you want to merge the changes and use the github PR squash feature or do you want me to create a branch and put the changes on a branch and create another PR?

**Comment by obfuscated** [comment]
> If the changes are okay do you want to merge the changes and use the github PR squash feature or do you want me to create a branch and put the changes on a branch and create another PR?

We use svn, so it will require a clean-up. Don't worry about it. Probably you'll have to retest, because I'm sure I'll have to do some style and more changes and I don't have cygwin/msys or whatever is needed (and I don't plan to install one).

**Comment by obfuscated** [comment]
> I have moved the Cygwin detection and path conversion into the SDK so these functions can then be used by the debugger plugin and the compiler plugins.

I don't like this. You've only done half the work... Let me see if I can come with something better.

**Comment by acotty** [comment]
What don't you like?
What is the half I have not done?
Does CB have a styling guide then? I have not seen one.

I have installed more Windows GCC compilers and now have the following installed for testing:
1) Cygwin
2) MSYS2 - Mingw64
3) MSYS2 - Mingw32
3) Mingw32 (same executables as bundled with CB 32 bit)
4) Mingw - from about 2013/2014
5) TDM-GCC - 32 bit
6) TDM-GCC - 64 bit

**Comment by obfuscated** [comment]
> What don't you like?

After the move reviewing the changes is impossible.
Using capital letters in filenames, inconsistent header/source spelling.
The naming of the functions.

> What is the half I have not done?

There are no changes to the build systems. You have to adjust all cbp files (4 of them) and the autotools build system.

**Comment by obfuscated** [comment]
Would it be possible to revert the state of this to before the move to global_cygwin.cpp/h?
I've tried to look at the code but there are so many problems and I'm not sure which are caused by you and which are old.

**Comment by acotty** [comment]
I can try to revert them, but it will mean that there will be duplicated code in the compiler & debugger plugins for Cygwin. I have some embedded dev to do tonight and will work on the revert tomorrow.
Are the problems in the non global_cygwin.cpp/h code or in the other files?

When you said there were 4 cbp files I can only see 3 (in the src directory) and only two of them are relevant as Cygwin is not applicable for unix. Where is the 4th one I should be looking at?

**Comment by obfuscated** [comment]
> I can try to revert them, but it will mean that there will be duplicated code in the compiler & debugger plugins for Cygwin. I have some embedded dev to do tonight and will work on the revert tomorrow.

Actually scratch that idea. Stop doing anything on this code and wait until I do the clean up work. Then I'll let you test the stuff and report if I've broken something.

> Are the problems in the non global_cygwin.cpp/h code or in the other files?

They are everywhere.

> When you said there were 4 cbp files I can only see 3 (in the src directory) and only two of them are relevant as Cygwin is not applicable for unix. Where is the 4th one I should be looking at?

This is one of my main concerns, everything is ifdefed for windows only and this makes the code ugly and hard to test (even if it compiles).

**Comment by acotty** [comment]
One thing that is not directly related to this PR, but is related to the windows and project files issue is the compiler/option XML files as some of them are windows only and only load on Windows. I have not looked to see if there are any that only load on Unix (Linux).
Like the project concerns for the Cygwin the same is also applicable for some of the compiler/option XML files. 
The next bit of work I am working on and have finished the main development is in https://sourceforge.net/p/codeblocks/tickets/374/ , but I need guidance as to what to do about the project files as they have the same/similar issue like the Cygwin changes w.r.t. the project files.

**Comment by obfuscated** [comment]
@acotty I've done one pass on the code. The changes are here: https://github.com/obfuscated/codeblocks_sf/tree/experiments/cygwin
Can you test if the code still works as expected?
There are several FIXMEs left in the code. The code cannot be committed/pushed before these are resolved. Would you be able to resolve some of those?

**Comment by acotty** [comment]
The code still works as expected. The testing is very simple:
1) Set a break point in a hello world cpp file
2) Run the debugger and check it starts. This did not occur in trunk. Lets say fix #1.
3) Check the break point occurs and is shown in the correct file and line number. Lets say this is fix #2. This did not occur in SVn even after fixing item 2) BTW.

I have some feedback:
1) I see you have prefixed allot of the variables and function names with cb, but the new files are not prefixed with cb. Should the news files be prefixed with cb like a bunch of other files in the SDK are?
2) Why are there auto make file changes?  These seem unrelated to the Cygwin fixes (apart from the makefile.am change)
3) I have not looked at the FIXMEs yet.

**Comment by obfuscated** [comment]
> I have some feedback:
> 
>     1. I see you have prefixed allot of the variables and function names with cb, but the new files are not prefixed with cb. Should the news files be prefixed with cb like a bunch of other files in the SDK are?

No idea. I don't have cygwin installed, so I don't know if it installs cygwin.h.

>     2. Why are there auto make file changes?  These seem unrelated to the Cygwin fixes (apart from the makefile.am change)

If you're talking about this d00b2f3709c5b5e6a5337a83aa9c4a31b6adf6c9 it was a mistake.

**Comment by acotty** [comment]
1) I was talking about the  src\sdk\cb*.cpp files with the prefix 'cb' and same with the src\include\scb*.h files also having the 'cb' prefix.  
2) Yes that was what I was talking about.

3) I didn't have the time to fork your branch etc. I have fixed all of the FIXME and retested with a two file project with a class that has a few printf's and one int variable and the testing worked with no issues or bug seen. Attached are the two updated files in the zip.
[update.zip](https://github.com/obfuscated/codeblocks_sf/files/6763646/update.zip)

**Comment by obfuscated** [comment]
Why have you closed this PR?

**Comment by acotty** [comment]
I didn't explicitly close it, Github closed it as I did a "git reset --hard <coimmit#>" on my master to go back to the commit before I made any cygwin changes as your changes are are going to be used and I though I should cleanup my master so it tracks your master aka SVN and use branches for the actual work I am doing. It did not even register that it would close PR's as I have deleted branches and that did not affect PR's that were merged.

I have proven a little bit of knowledge can be dangerous thing.

**Comment by obfuscated** [comment]
@acotty I've pushed your latest changes to the `experiments/cygwin` branch. I've also done a bit more cleaning on top. Please test and report if it still works.

**Comment by acotty** [comment]
@obfuscated I made  two changes in the time since the last changes as follows:
1) Move the #include <wx/msw/registry.h>so C::B win32 builds do not fail.
2) Added wxDirExists in case the registry does not have the Cygwin entries.

Today I also changed the wxString() to wxEmptyString to match the other changes that you have been doing lately.

Once I finish my testing I will create a PR against the experiments/cygwin branch as I needed to create a new branch based on this to ensure that the PR was clean with regards to Github not including files that are the same.

**Pull request closed without merging**
